<?php


/**
 * This class adds structure of 'fs_beta_invitations' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Mar 11 23:15:47 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FsBetaInvitationsMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FsBetaInvitationsMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(FsBetaInvitationsPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(FsBetaInvitationsPeer::TABLE_NAME);
		$tMap->setPhpName('FsBetaInvitations');
		$tMap->setClassname('FsBetaInvitations');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('INVITE_ID', 'InviteId', 'INTEGER', true, null);

		$tMap->addColumn('INVITE_CODE', 'InviteCode', 'VARCHAR', false, 16);

		$tMap->addColumn('INVITE_ALLOWANCE', 'InviteAllowance', 'INTEGER', false, null);

		$tMap->addColumn('INVITE_USED', 'InviteUsed', 'INTEGER', false, null);

	} // doBuild()

} // FsBetaInvitationsMapBuilder
