<?php


/**
 * This class adds structure of 'fs_films' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Mar 11 23:15:47 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FsFilmsMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FsFilmsMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(FsFilmsPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(FsFilmsPeer::TABLE_NAME);
		$tMap->setPhpName('FsFilms');
		$tMap->setClassname('FsFilms');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('FILM_ID', 'FilmId', 'INTEGER', true, null);

		$tMap->addColumn('FILM_TITLE', 'FilmTitle', 'VARCHAR', true, 64);

		$tMap->addColumn('FILM_WIKIPEDIA_TITLE', 'FilmWikipediaTitle', 'VARCHAR', true, 64);

		$tMap->addColumn('FILM_WIKIPEDIA_POSTER', 'FilmWikipediaPoster', 'VARCHAR', false, 256);

		$tMap->addColumn('FILM_WIKIPEDIA_SUMMARY', 'FilmWikipediaSummary', 'LONGVARCHAR', false, null);

		$tMap->addColumn('FILM_RELEASE', 'FilmRelease', 'DATE', true, null);

		$tMap->addColumn('FILM_WIKIPEDIA_REVISION', 'FilmWikipediaRevision', 'INTEGER', false, null);

		$tMap->addColumn('NEXT_SYNC', 'NextSync', 'TIMESTAMP', false, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // FsFilmsMapBuilder
