<?php


/**
 * This class adds structure of 'fs_stacks' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Mar 11 23:15:47 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FsStacksMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FsStacksMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(FsStacksPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(FsStacksPeer::TABLE_NAME);
		$tMap->setPhpName('FsStacks');
		$tMap->setClassname('FsStacks');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('STACK_ID', 'StackId', 'INTEGER', true, null);

		$tMap->addForeignKey('FILM_ID', 'FilmId', 'INTEGER', 'fs_films', 'FILM_ID', true, null);

		$tMap->addForeignKey('USER_ID', 'UserId', 'INTEGER', 'sf_guard_user', 'ID', true, null);

		$tMap->addForeignKey('WORD_ID', 'WordId', 'INTEGER', 'fs_stacks_words', 'WORD_ID', false, null);

		$tMap->addColumn('GROUP_ID', 'GroupId', 'INTEGER', false, null);

		$tMap->addColumn('STACK_SEEN_COUNT', 'StackSeenCount', 'INTEGER', false, null);

		$tMap->addColumn('STACK_WATCHDATE', 'StackWatchdate', 'DATE', true, null);

		$tMap->addColumn('STACK_RECOMMEND', 'StackRecommend', 'BOOLEAN', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // FsStacksMapBuilder
