<?php

/**
 * Base class that represents a row from the 'sf_guard_user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Mar 11 23:15:47 2009
 *
 * @package    lib.model.om
 */
abstract class BasesfGuardUserProfile extends BaseObject  implements Persistent {


  const PEER = 'sfGuardUserProfilePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        sfGuardUserProfilePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the user_email field.
	 * @var        string
	 */
	protected $user_email;

	/**
	 * The value for the user_about field.
	 * @var        string
	 */
	protected $user_about;

	/**
	 * The value for the user_country field.
	 * @var        string
	 */
	protected $user_country;

	/**
	 * The value for the user_first_name field.
	 * @var        string
	 */
	protected $user_first_name;

	/**
	 * The value for the user_last_name field.
	 * @var        string
	 */
	protected $user_last_name;

	/**
	 * The value for the user_twitter_uname field.
	 * @var        string
	 */
	protected $user_twitter_uname;

	/**
	 * The value for the user_twitter_pword field.
	 * @var        string
	 */
	protected $user_twitter_pword;

	/**
	 * The value for the user_twitter_bool field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $user_twitter_bool;

	/**
	 * The value for the user_avatar_file field.
	 * @var        string
	 */
	protected $user_avatar_file;

	/**
	 * The value for the user_dob field.
	 * @var        string
	 */
	protected $user_dob;

	/**
	 * The value for the user_privacy_level field.
	 * Note: this column has a database default value of: 0
	 * @var        int
	 */
	protected $user_privacy_level;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUser;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasesfGuardUserProfile object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->user_twitter_bool = 0;
		$this->user_privacy_level = 0;
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [user_email] column value.
	 * 
	 * @return     string
	 */
	public function getUserEmail()
	{
		return $this->user_email;
	}

	/**
	 * Get the [user_about] column value.
	 * 
	 * @return     string
	 */
	public function getUserAbout()
	{
		return $this->user_about;
	}

	/**
	 * Get the [user_country] column value.
	 * 
	 * @return     string
	 */
	public function getUserCountry()
	{
		return $this->user_country;
	}

	/**
	 * Get the [user_first_name] column value.
	 * 
	 * @return     string
	 */
	public function getUserFirstName()
	{
		return $this->user_first_name;
	}

	/**
	 * Get the [user_last_name] column value.
	 * 
	 * @return     string
	 */
	public function getUserLastName()
	{
		return $this->user_last_name;
	}

	/**
	 * Get the [user_twitter_uname] column value.
	 * 
	 * @return     string
	 */
	public function getUserTwitterUname()
	{
		return $this->user_twitter_uname;
	}

	/**
	 * Get the [user_twitter_pword] column value.
	 * 
	 * @return     string
	 */
	public function getUserTwitterPword()
	{
		return $this->user_twitter_pword;
	}

	/**
	 * Get the [user_twitter_bool] column value.
	 * 
	 * @return     int
	 */
	public function getUserTwitterBool()
	{
		return $this->user_twitter_bool;
	}

	/**
	 * Get the [user_avatar_file] column value.
	 * 
	 * @return     string
	 */
	public function getUserAvatarFile()
	{
		return $this->user_avatar_file;
	}

	/**
	 * Get the [optionally formatted] temporal [user_dob] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUserDob($format = 'Y-m-d')
	{
		if ($this->user_dob === null) {
			return null;
		}


		if ($this->user_dob === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->user_dob);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->user_dob, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [user_privacy_level] column value.
	 * 
	 * @return     int
	 */
	public function getUserPrivacyLevel()
	{
		return $this->user_privacy_level;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_ID;
		}

		if ($this->asfGuardUser !== null && $this->asfGuardUser->getId() !== $v) {
			$this->asfGuardUser = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [user_email] column.
	 * 
	 * @param      string $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_email !== $v) {
			$this->user_email = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_EMAIL;
		}

		return $this;
	} // setUserEmail()

	/**
	 * Set the value of [user_about] column.
	 * 
	 * @param      string $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserAbout($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_about !== $v) {
			$this->user_about = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_ABOUT;
		}

		return $this;
	} // setUserAbout()

	/**
	 * Set the value of [user_country] column.
	 * 
	 * @param      string $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserCountry($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_country !== $v) {
			$this->user_country = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_COUNTRY;
		}

		return $this;
	} // setUserCountry()

	/**
	 * Set the value of [user_first_name] column.
	 * 
	 * @param      string $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserFirstName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_first_name !== $v) {
			$this->user_first_name = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_FIRST_NAME;
		}

		return $this;
	} // setUserFirstName()

	/**
	 * Set the value of [user_last_name] column.
	 * 
	 * @param      string $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserLastName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_last_name !== $v) {
			$this->user_last_name = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_LAST_NAME;
		}

		return $this;
	} // setUserLastName()

	/**
	 * Set the value of [user_twitter_uname] column.
	 * 
	 * @param      string $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserTwitterUname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_twitter_uname !== $v) {
			$this->user_twitter_uname = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_TWITTER_UNAME;
		}

		return $this;
	} // setUserTwitterUname()

	/**
	 * Set the value of [user_twitter_pword] column.
	 * 
	 * @param      string $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserTwitterPword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_twitter_pword !== $v) {
			$this->user_twitter_pword = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_TWITTER_PWORD;
		}

		return $this;
	} // setUserTwitterPword()

	/**
	 * Set the value of [user_twitter_bool] column.
	 * 
	 * @param      int $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserTwitterBool($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_twitter_bool !== $v || $v === 0) {
			$this->user_twitter_bool = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_TWITTER_BOOL;
		}

		return $this;
	} // setUserTwitterBool()

	/**
	 * Set the value of [user_avatar_file] column.
	 * 
	 * @param      string $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserAvatarFile($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->user_avatar_file !== $v) {
			$this->user_avatar_file = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_AVATAR_FILE;
		}

		return $this;
	} // setUserAvatarFile()

	/**
	 * Sets the value of [user_dob] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserDob($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->user_dob !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->user_dob !== null && $tmpDt = new DateTime($this->user_dob)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->user_dob = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_DOB;
			}
		} // if either are not null

		return $this;
	} // setUserDob()

	/**
	 * Set the value of [user_privacy_level] column.
	 * 
	 * @param      int $v new value
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 */
	public function setUserPrivacyLevel($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_privacy_level !== $v || $v === 0) {
			$this->user_privacy_level = $v;
			$this->modifiedColumns[] = sfGuardUserProfilePeer::USER_PRIVACY_LEVEL;
		}

		return $this;
	} // setUserPrivacyLevel()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(sfGuardUserProfilePeer::USER_TWITTER_BOOL,sfGuardUserProfilePeer::USER_PRIVACY_LEVEL))) {
				return false;
			}

			if ($this->user_twitter_bool !== 0) {
				return false;
			}

			if ($this->user_privacy_level !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->user_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->user_email = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->user_about = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->user_country = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->user_first_name = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->user_last_name = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->user_twitter_uname = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->user_twitter_pword = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->user_twitter_bool = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->user_avatar_file = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->user_dob = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->user_privacy_level = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 13; // 13 = sfGuardUserProfilePeer::NUM_COLUMNS - sfGuardUserProfilePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating sfGuardUserProfile object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfGuardUser !== null && $this->user_id !== $this->asfGuardUser->getId()) {
			$this->asfGuardUser = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserProfilePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = sfGuardUserProfilePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfGuardUser = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasesfGuardUserProfile:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserProfilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			sfGuardUserProfilePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasesfGuardUserProfile:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasesfGuardUserProfile:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserProfilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasesfGuardUserProfile:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			sfGuardUserProfilePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUser !== null) {
				if ($this->asfGuardUser->isModified() || $this->asfGuardUser->isNew()) {
					$affectedRows += $this->asfGuardUser->save($con);
				}
				$this->setsfGuardUser($this->asfGuardUser);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = sfGuardUserProfilePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = sfGuardUserProfilePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += sfGuardUserProfilePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUser !== null) {
				if (!$this->asfGuardUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUser->getValidationFailures());
				}
			}


			if (($retval = sfGuardUserProfilePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfGuardUserProfilePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getUserId();
				break;
			case 2:
				return $this->getUserEmail();
				break;
			case 3:
				return $this->getUserAbout();
				break;
			case 4:
				return $this->getUserCountry();
				break;
			case 5:
				return $this->getUserFirstName();
				break;
			case 6:
				return $this->getUserLastName();
				break;
			case 7:
				return $this->getUserTwitterUname();
				break;
			case 8:
				return $this->getUserTwitterPword();
				break;
			case 9:
				return $this->getUserTwitterBool();
				break;
			case 10:
				return $this->getUserAvatarFile();
				break;
			case 11:
				return $this->getUserDob();
				break;
			case 12:
				return $this->getUserPrivacyLevel();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = sfGuardUserProfilePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getUserId(),
			$keys[2] => $this->getUserEmail(),
			$keys[3] => $this->getUserAbout(),
			$keys[4] => $this->getUserCountry(),
			$keys[5] => $this->getUserFirstName(),
			$keys[6] => $this->getUserLastName(),
			$keys[7] => $this->getUserTwitterUname(),
			$keys[8] => $this->getUserTwitterPword(),
			$keys[9] => $this->getUserTwitterBool(),
			$keys[10] => $this->getUserAvatarFile(),
			$keys[11] => $this->getUserDob(),
			$keys[12] => $this->getUserPrivacyLevel(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfGuardUserProfilePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setUserId($value);
				break;
			case 2:
				$this->setUserEmail($value);
				break;
			case 3:
				$this->setUserAbout($value);
				break;
			case 4:
				$this->setUserCountry($value);
				break;
			case 5:
				$this->setUserFirstName($value);
				break;
			case 6:
				$this->setUserLastName($value);
				break;
			case 7:
				$this->setUserTwitterUname($value);
				break;
			case 8:
				$this->setUserTwitterPword($value);
				break;
			case 9:
				$this->setUserTwitterBool($value);
				break;
			case 10:
				$this->setUserAvatarFile($value);
				break;
			case 11:
				$this->setUserDob($value);
				break;
			case 12:
				$this->setUserPrivacyLevel($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = sfGuardUserProfilePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUserId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUserEmail($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setUserAbout($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setUserCountry($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setUserFirstName($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setUserLastName($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setUserTwitterUname($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setUserTwitterPword($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUserTwitterBool($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setUserAvatarFile($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setUserDob($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setUserPrivacyLevel($arr[$keys[12]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(sfGuardUserProfilePeer::DATABASE_NAME);

		if ($this->isColumnModified(sfGuardUserProfilePeer::ID)) $criteria->add(sfGuardUserProfilePeer::ID, $this->id);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_ID)) $criteria->add(sfGuardUserProfilePeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_EMAIL)) $criteria->add(sfGuardUserProfilePeer::USER_EMAIL, $this->user_email);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_ABOUT)) $criteria->add(sfGuardUserProfilePeer::USER_ABOUT, $this->user_about);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_COUNTRY)) $criteria->add(sfGuardUserProfilePeer::USER_COUNTRY, $this->user_country);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_FIRST_NAME)) $criteria->add(sfGuardUserProfilePeer::USER_FIRST_NAME, $this->user_first_name);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_LAST_NAME)) $criteria->add(sfGuardUserProfilePeer::USER_LAST_NAME, $this->user_last_name);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_TWITTER_UNAME)) $criteria->add(sfGuardUserProfilePeer::USER_TWITTER_UNAME, $this->user_twitter_uname);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_TWITTER_PWORD)) $criteria->add(sfGuardUserProfilePeer::USER_TWITTER_PWORD, $this->user_twitter_pword);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_TWITTER_BOOL)) $criteria->add(sfGuardUserProfilePeer::USER_TWITTER_BOOL, $this->user_twitter_bool);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_AVATAR_FILE)) $criteria->add(sfGuardUserProfilePeer::USER_AVATAR_FILE, $this->user_avatar_file);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_DOB)) $criteria->add(sfGuardUserProfilePeer::USER_DOB, $this->user_dob);
		if ($this->isColumnModified(sfGuardUserProfilePeer::USER_PRIVACY_LEVEL)) $criteria->add(sfGuardUserProfilePeer::USER_PRIVACY_LEVEL, $this->user_privacy_level);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(sfGuardUserProfilePeer::DATABASE_NAME);

		$criteria->add(sfGuardUserProfilePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of sfGuardUserProfile (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUserId($this->user_id);

		$copyObj->setUserEmail($this->user_email);

		$copyObj->setUserAbout($this->user_about);

		$copyObj->setUserCountry($this->user_country);

		$copyObj->setUserFirstName($this->user_first_name);

		$copyObj->setUserLastName($this->user_last_name);

		$copyObj->setUserTwitterUname($this->user_twitter_uname);

		$copyObj->setUserTwitterPword($this->user_twitter_pword);

		$copyObj->setUserTwitterBool($this->user_twitter_bool);

		$copyObj->setUserAvatarFile($this->user_avatar_file);

		$copyObj->setUserDob($this->user_dob);

		$copyObj->setUserPrivacyLevel($this->user_privacy_level);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     sfGuardUserProfile Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     sfGuardUserProfilePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new sfGuardUserProfilePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     sfGuardUserProfile The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUser(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->asfGuardUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addsfGuardUserProfile($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUser(PropelPDO $con = null)
	{
		if ($this->asfGuardUser === null && ($this->user_id !== null)) {
			$c = new Criteria(sfGuardUserPeer::DATABASE_NAME);
			$c->add(sfGuardUserPeer::ID, $this->user_id);
			$this->asfGuardUser = sfGuardUserPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUser->addsfGuardUserProfiles($this);
			 */
		}
		return $this->asfGuardUser;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->asfGuardUser = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasesfGuardUserProfile:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasesfGuardUserProfile::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasesfGuardUserProfile
