<?php

/**
 * Base class that represents a row from the 'fs_stacks' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Mar 11 23:15:47 2009
 *
 * @package    lib.model.om
 */
abstract class BaseFsStacks extends BaseObject  implements Persistent {


  const PEER = 'FsStacksPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FsStacksPeer
	 */
	protected static $peer;

	/**
	 * The value for the stack_id field.
	 * @var        int
	 */
	protected $stack_id;

	/**
	 * The value for the film_id field.
	 * @var        int
	 */
	protected $film_id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the word_id field.
	 * @var        int
	 */
	protected $word_id;

	/**
	 * The value for the group_id field.
	 * @var        int
	 */
	protected $group_id;

	/**
	 * The value for the stack_seen_count field.
	 * @var        int
	 */
	protected $stack_seen_count;

	/**
	 * The value for the stack_watchdate field.
	 * @var        string
	 */
	protected $stack_watchdate;

	/**
	 * The value for the stack_recommend field.
	 * @var        boolean
	 */
	protected $stack_recommend;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        FsFilms
	 */
	protected $aFsFilms;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUser;

	/**
	 * @var        FsStacksWords
	 */
	protected $aFsStacksWords;

	/**
	 * @var        array FsStacksGroups[] Collection to store aggregation of FsStacksGroups objects.
	 */
	protected $collFsStacksGroupss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFsStacksGroupss.
	 */
	private $lastFsStacksGroupsCriteria = null;

	/**
	 * @var        array FsStacksComments[] Collection to store aggregation of FsStacksComments objects.
	 */
	protected $collFsStacksCommentss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFsStacksCommentss.
	 */
	private $lastFsStacksCommentsCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseFsStacks object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [stack_id] column value.
	 * 
	 * @return     int
	 */
	public function getStackId()
	{
		return $this->stack_id;
	}

	/**
	 * Get the [film_id] column value.
	 * 
	 * @return     int
	 */
	public function getFilmId()
	{
		return $this->film_id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [word_id] column value.
	 * 
	 * @return     int
	 */
	public function getWordId()
	{
		return $this->word_id;
	}

	/**
	 * Get the [group_id] column value.
	 * 
	 * @return     int
	 */
	public function getGroupId()
	{
		return $this->group_id;
	}

	/**
	 * Get the [stack_seen_count] column value.
	 * 
	 * @return     int
	 */
	public function getStackSeenCount()
	{
		return $this->stack_seen_count;
	}

	/**
	 * Get the [optionally formatted] temporal [stack_watchdate] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getStackWatchdate($format = 'Y-m-d')
	{
		if ($this->stack_watchdate === null) {
			return null;
		}


		if ($this->stack_watchdate === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->stack_watchdate);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->stack_watchdate, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [stack_recommend] column value.
	 * 
	 * @return     boolean
	 */
	public function getStackRecommend()
	{
		return $this->stack_recommend;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [stack_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FsStacks The current object (for fluent API support)
	 */
	public function setStackId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stack_id !== $v) {
			$this->stack_id = $v;
			$this->modifiedColumns[] = FsStacksPeer::STACK_ID;
		}

		return $this;
	} // setStackId()

	/**
	 * Set the value of [film_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FsStacks The current object (for fluent API support)
	 */
	public function setFilmId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->film_id !== $v) {
			$this->film_id = $v;
			$this->modifiedColumns[] = FsStacksPeer::FILM_ID;
		}

		if ($this->aFsFilms !== null && $this->aFsFilms->getFilmId() !== $v) {
			$this->aFsFilms = null;
		}

		return $this;
	} // setFilmId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FsStacks The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = FsStacksPeer::USER_ID;
		}

		if ($this->asfGuardUser !== null && $this->asfGuardUser->getId() !== $v) {
			$this->asfGuardUser = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [word_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FsStacks The current object (for fluent API support)
	 */
	public function setWordId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->word_id !== $v) {
			$this->word_id = $v;
			$this->modifiedColumns[] = FsStacksPeer::WORD_ID;
		}

		if ($this->aFsStacksWords !== null && $this->aFsStacksWords->getWordId() !== $v) {
			$this->aFsStacksWords = null;
		}

		return $this;
	} // setWordId()

	/**
	 * Set the value of [group_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FsStacks The current object (for fluent API support)
	 */
	public function setGroupId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->group_id !== $v) {
			$this->group_id = $v;
			$this->modifiedColumns[] = FsStacksPeer::GROUP_ID;
		}

		return $this;
	} // setGroupId()

	/**
	 * Set the value of [stack_seen_count] column.
	 * 
	 * @param      int $v new value
	 * @return     FsStacks The current object (for fluent API support)
	 */
	public function setStackSeenCount($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stack_seen_count !== $v) {
			$this->stack_seen_count = $v;
			$this->modifiedColumns[] = FsStacksPeer::STACK_SEEN_COUNT;
		}

		return $this;
	} // setStackSeenCount()

	/**
	 * Sets the value of [stack_watchdate] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     FsStacks The current object (for fluent API support)
	 */
	public function setStackWatchdate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->stack_watchdate !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->stack_watchdate !== null && $tmpDt = new DateTime($this->stack_watchdate)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->stack_watchdate = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = FsStacksPeer::STACK_WATCHDATE;
			}
		} // if either are not null

		return $this;
	} // setStackWatchdate()

	/**
	 * Set the value of [stack_recommend] column.
	 * 
	 * @param      boolean $v new value
	 * @return     FsStacks The current object (for fluent API support)
	 */
	public function setStackRecommend($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->stack_recommend !== $v) {
			$this->stack_recommend = $v;
			$this->modifiedColumns[] = FsStacksPeer::STACK_RECOMMEND;
		}

		return $this;
	} // setStackRecommend()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     FsStacks The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FsStacksPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->stack_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->film_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->user_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->word_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->group_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->stack_seen_count = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->stack_watchdate = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->stack_recommend = ($row[$startcol + 7] !== null) ? (boolean) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 9; // 9 = FsStacksPeer::NUM_COLUMNS - FsStacksPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating FsStacks object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aFsFilms !== null && $this->film_id !== $this->aFsFilms->getFilmId()) {
			$this->aFsFilms = null;
		}
		if ($this->asfGuardUser !== null && $this->user_id !== $this->asfGuardUser->getId()) {
			$this->asfGuardUser = null;
		}
		if ($this->aFsStacksWords !== null && $this->word_id !== $this->aFsStacksWords->getWordId()) {
			$this->aFsStacksWords = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FsStacksPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FsStacksPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aFsFilms = null;
			$this->asfGuardUser = null;
			$this->aFsStacksWords = null;
			$this->collFsStacksGroupss = null;
			$this->lastFsStacksGroupsCriteria = null;

			$this->collFsStacksCommentss = null;
			$this->lastFsStacksCommentsCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFsStacks:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FsStacksPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			FsStacksPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseFsStacks:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFsStacks:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(FsStacksPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FsStacksPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseFsStacks:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			FsStacksPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aFsFilms !== null) {
				if ($this->aFsFilms->isModified() || $this->aFsFilms->isNew()) {
					$affectedRows += $this->aFsFilms->save($con);
				}
				$this->setFsFilms($this->aFsFilms);
			}

			if ($this->asfGuardUser !== null) {
				if ($this->asfGuardUser->isModified() || $this->asfGuardUser->isNew()) {
					$affectedRows += $this->asfGuardUser->save($con);
				}
				$this->setsfGuardUser($this->asfGuardUser);
			}

			if ($this->aFsStacksWords !== null) {
				if ($this->aFsStacksWords->isModified() || $this->aFsStacksWords->isNew()) {
					$affectedRows += $this->aFsStacksWords->save($con);
				}
				$this->setFsStacksWords($this->aFsStacksWords);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FsStacksPeer::STACK_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FsStacksPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setStackId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FsStacksPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collFsStacksGroupss !== null) {
				foreach ($this->collFsStacksGroupss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collFsStacksCommentss !== null) {
				foreach ($this->collFsStacksCommentss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aFsFilms !== null) {
				if (!$this->aFsFilms->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aFsFilms->getValidationFailures());
				}
			}

			if ($this->asfGuardUser !== null) {
				if (!$this->asfGuardUser->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUser->getValidationFailures());
				}
			}

			if ($this->aFsStacksWords !== null) {
				if (!$this->aFsStacksWords->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aFsStacksWords->getValidationFailures());
				}
			}


			if (($retval = FsStacksPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collFsStacksGroupss !== null) {
					foreach ($this->collFsStacksGroupss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collFsStacksCommentss !== null) {
					foreach ($this->collFsStacksCommentss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FsStacksPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getStackId();
				break;
			case 1:
				return $this->getFilmId();
				break;
			case 2:
				return $this->getUserId();
				break;
			case 3:
				return $this->getWordId();
				break;
			case 4:
				return $this->getGroupId();
				break;
			case 5:
				return $this->getStackSeenCount();
				break;
			case 6:
				return $this->getStackWatchdate();
				break;
			case 7:
				return $this->getStackRecommend();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FsStacksPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getStackId(),
			$keys[1] => $this->getFilmId(),
			$keys[2] => $this->getUserId(),
			$keys[3] => $this->getWordId(),
			$keys[4] => $this->getGroupId(),
			$keys[5] => $this->getStackSeenCount(),
			$keys[6] => $this->getStackWatchdate(),
			$keys[7] => $this->getStackRecommend(),
			$keys[8] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FsStacksPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setStackId($value);
				break;
			case 1:
				$this->setFilmId($value);
				break;
			case 2:
				$this->setUserId($value);
				break;
			case 3:
				$this->setWordId($value);
				break;
			case 4:
				$this->setGroupId($value);
				break;
			case 5:
				$this->setStackSeenCount($value);
				break;
			case 6:
				$this->setStackWatchdate($value);
				break;
			case 7:
				$this->setStackRecommend($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FsStacksPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setStackId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setFilmId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setUserId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setWordId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setGroupId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setStackSeenCount($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setStackWatchdate($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setStackRecommend($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FsStacksPeer::DATABASE_NAME);

		if ($this->isColumnModified(FsStacksPeer::STACK_ID)) $criteria->add(FsStacksPeer::STACK_ID, $this->stack_id);
		if ($this->isColumnModified(FsStacksPeer::FILM_ID)) $criteria->add(FsStacksPeer::FILM_ID, $this->film_id);
		if ($this->isColumnModified(FsStacksPeer::USER_ID)) $criteria->add(FsStacksPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(FsStacksPeer::WORD_ID)) $criteria->add(FsStacksPeer::WORD_ID, $this->word_id);
		if ($this->isColumnModified(FsStacksPeer::GROUP_ID)) $criteria->add(FsStacksPeer::GROUP_ID, $this->group_id);
		if ($this->isColumnModified(FsStacksPeer::STACK_SEEN_COUNT)) $criteria->add(FsStacksPeer::STACK_SEEN_COUNT, $this->stack_seen_count);
		if ($this->isColumnModified(FsStacksPeer::STACK_WATCHDATE)) $criteria->add(FsStacksPeer::STACK_WATCHDATE, $this->stack_watchdate);
		if ($this->isColumnModified(FsStacksPeer::STACK_RECOMMEND)) $criteria->add(FsStacksPeer::STACK_RECOMMEND, $this->stack_recommend);
		if ($this->isColumnModified(FsStacksPeer::CREATED_AT)) $criteria->add(FsStacksPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FsStacksPeer::DATABASE_NAME);

		$criteria->add(FsStacksPeer::STACK_ID, $this->stack_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getStackId();
	}

	/**
	 * Generic method to set the primary key (stack_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setStackId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of FsStacks (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFilmId($this->film_id);

		$copyObj->setUserId($this->user_id);

		$copyObj->setWordId($this->word_id);

		$copyObj->setGroupId($this->group_id);

		$copyObj->setStackSeenCount($this->stack_seen_count);

		$copyObj->setStackWatchdate($this->stack_watchdate);

		$copyObj->setStackRecommend($this->stack_recommend);

		$copyObj->setCreatedAt($this->created_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getFsStacksGroupss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFsStacksGroups($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getFsStacksCommentss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFsStacksComments($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setStackId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     FsStacks Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FsStacksPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FsStacksPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a FsFilms object.
	 *
	 * @param      FsFilms $v
	 * @return     FsStacks The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setFsFilms(FsFilms $v = null)
	{
		if ($v === null) {
			$this->setFilmId(NULL);
		} else {
			$this->setFilmId($v->getFilmId());
		}

		$this->aFsFilms = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the FsFilms object, it will not be re-added.
		if ($v !== null) {
			$v->addFsStacks($this);
		}

		return $this;
	}


	/**
	 * Get the associated FsFilms object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     FsFilms The associated FsFilms object.
	 * @throws     PropelException
	 */
	public function getFsFilms(PropelPDO $con = null)
	{
		if ($this->aFsFilms === null && ($this->film_id !== null)) {
			$c = new Criteria(FsFilmsPeer::DATABASE_NAME);
			$c->add(FsFilmsPeer::FILM_ID, $this->film_id);
			$this->aFsFilms = FsFilmsPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aFsFilms->addFsStackss($this);
			 */
		}
		return $this->aFsFilms;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     FsStacks The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUser(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->asfGuardUser = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addFsStacks($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUser(PropelPDO $con = null)
	{
		if ($this->asfGuardUser === null && ($this->user_id !== null)) {
			$c = new Criteria(sfGuardUserPeer::DATABASE_NAME);
			$c->add(sfGuardUserPeer::ID, $this->user_id);
			$this->asfGuardUser = sfGuardUserPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUser->addFsStackss($this);
			 */
		}
		return $this->asfGuardUser;
	}

	/**
	 * Declares an association between this object and a FsStacksWords object.
	 *
	 * @param      FsStacksWords $v
	 * @return     FsStacks The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setFsStacksWords(FsStacksWords $v = null)
	{
		if ($v === null) {
			$this->setWordId(NULL);
		} else {
			$this->setWordId($v->getWordId());
		}

		$this->aFsStacksWords = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the FsStacksWords object, it will not be re-added.
		if ($v !== null) {
			$v->addFsStacks($this);
		}

		return $this;
	}


	/**
	 * Get the associated FsStacksWords object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     FsStacksWords The associated FsStacksWords object.
	 * @throws     PropelException
	 */
	public function getFsStacksWords(PropelPDO $con = null)
	{
		if ($this->aFsStacksWords === null && ($this->word_id !== null)) {
			$c = new Criteria(FsStacksWordsPeer::DATABASE_NAME);
			$c->add(FsStacksWordsPeer::WORD_ID, $this->word_id);
			$this->aFsStacksWords = FsStacksWordsPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aFsStacksWords->addFsStackss($this);
			 */
		}
		return $this->aFsStacksWords;
	}

	/**
	 * Clears out the collFsStacksGroupss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFsStacksGroupss()
	 */
	public function clearFsStacksGroupss()
	{
		$this->collFsStacksGroupss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFsStacksGroupss collection (array).
	 *
	 * By default this just sets the collFsStacksGroupss collection to an empty array (like clearcollFsStacksGroupss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFsStacksGroupss()
	{
		$this->collFsStacksGroupss = array();
	}

	/**
	 * Gets an array of FsStacksGroups objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this FsStacks has previously been saved, it will retrieve
	 * related FsStacksGroupss from storage. If this FsStacks is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array FsStacksGroups[]
	 * @throws     PropelException
	 */
	public function getFsStacksGroupss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsStacksPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFsStacksGroupss === null) {
			if ($this->isNew()) {
			   $this->collFsStacksGroupss = array();
			} else {

				$criteria->add(FsStacksGroupsPeer::STACK_ID, $this->stack_id);

				FsStacksGroupsPeer::addSelectColumns($criteria);
				$this->collFsStacksGroupss = FsStacksGroupsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FsStacksGroupsPeer::STACK_ID, $this->stack_id);

				FsStacksGroupsPeer::addSelectColumns($criteria);
				if (!isset($this->lastFsStacksGroupsCriteria) || !$this->lastFsStacksGroupsCriteria->equals($criteria)) {
					$this->collFsStacksGroupss = FsStacksGroupsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFsStacksGroupsCriteria = $criteria;
		return $this->collFsStacksGroupss;
	}

	/**
	 * Returns the number of related FsStacksGroups objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related FsStacksGroups objects.
	 * @throws     PropelException
	 */
	public function countFsStacksGroupss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsStacksPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFsStacksGroupss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FsStacksGroupsPeer::STACK_ID, $this->stack_id);

				$count = FsStacksGroupsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FsStacksGroupsPeer::STACK_ID, $this->stack_id);

				if (!isset($this->lastFsStacksGroupsCriteria) || !$this->lastFsStacksGroupsCriteria->equals($criteria)) {
					$count = FsStacksGroupsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collFsStacksGroupss);
				}
			} else {
				$count = count($this->collFsStacksGroupss);
			}
		}
		$this->lastFsStacksGroupsCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a FsStacksGroups object to this object
	 * through the FsStacksGroups foreign key attribute.
	 *
	 * @param      FsStacksGroups $l FsStacksGroups
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFsStacksGroups(FsStacksGroups $l)
	{
		if ($this->collFsStacksGroupss === null) {
			$this->initFsStacksGroupss();
		}
		if (!in_array($l, $this->collFsStacksGroupss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFsStacksGroupss, $l);
			$l->setFsStacks($this);
		}
	}

	/**
	 * Clears out the collFsStacksCommentss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFsStacksCommentss()
	 */
	public function clearFsStacksCommentss()
	{
		$this->collFsStacksCommentss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFsStacksCommentss collection (array).
	 *
	 * By default this just sets the collFsStacksCommentss collection to an empty array (like clearcollFsStacksCommentss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFsStacksCommentss()
	{
		$this->collFsStacksCommentss = array();
	}

	/**
	 * Gets an array of FsStacksComments objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this FsStacks has previously been saved, it will retrieve
	 * related FsStacksCommentss from storage. If this FsStacks is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array FsStacksComments[]
	 * @throws     PropelException
	 */
	public function getFsStacksCommentss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsStacksPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFsStacksCommentss === null) {
			if ($this->isNew()) {
			   $this->collFsStacksCommentss = array();
			} else {

				$criteria->add(FsStacksCommentsPeer::STACK_ID, $this->stack_id);

				FsStacksCommentsPeer::addSelectColumns($criteria);
				$this->collFsStacksCommentss = FsStacksCommentsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FsStacksCommentsPeer::STACK_ID, $this->stack_id);

				FsStacksCommentsPeer::addSelectColumns($criteria);
				if (!isset($this->lastFsStacksCommentsCriteria) || !$this->lastFsStacksCommentsCriteria->equals($criteria)) {
					$this->collFsStacksCommentss = FsStacksCommentsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFsStacksCommentsCriteria = $criteria;
		return $this->collFsStacksCommentss;
	}

	/**
	 * Returns the number of related FsStacksComments objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related FsStacksComments objects.
	 * @throws     PropelException
	 */
	public function countFsStacksCommentss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsStacksPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFsStacksCommentss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FsStacksCommentsPeer::STACK_ID, $this->stack_id);

				$count = FsStacksCommentsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FsStacksCommentsPeer::STACK_ID, $this->stack_id);

				if (!isset($this->lastFsStacksCommentsCriteria) || !$this->lastFsStacksCommentsCriteria->equals($criteria)) {
					$count = FsStacksCommentsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collFsStacksCommentss);
				}
			} else {
				$count = count($this->collFsStacksCommentss);
			}
		}
		$this->lastFsStacksCommentsCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a FsStacksComments object to this object
	 * through the FsStacksComments foreign key attribute.
	 *
	 * @param      FsStacksComments $l FsStacksComments
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFsStacksComments(FsStacksComments $l)
	{
		if ($this->collFsStacksCommentss === null) {
			$this->initFsStacksCommentss();
		}
		if (!in_array($l, $this->collFsStacksCommentss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFsStacksCommentss, $l);
			$l->setFsStacks($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this FsStacks is new, it will return
	 * an empty collection; or if this FsStacks has previously
	 * been saved, it will retrieve related FsStacksCommentss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in FsStacks.
	 */
	public function getFsStacksCommentssJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsStacksPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFsStacksCommentss === null) {
			if ($this->isNew()) {
				$this->collFsStacksCommentss = array();
			} else {

				$criteria->add(FsStacksCommentsPeer::STACK_ID, $this->stack_id);

				$this->collFsStacksCommentss = FsStacksCommentsPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FsStacksCommentsPeer::STACK_ID, $this->stack_id);

			if (!isset($this->lastFsStacksCommentsCriteria) || !$this->lastFsStacksCommentsCriteria->equals($criteria)) {
				$this->collFsStacksCommentss = FsStacksCommentsPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastFsStacksCommentsCriteria = $criteria;

		return $this->collFsStacksCommentss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collFsStacksGroupss) {
				foreach ((array) $this->collFsStacksGroupss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collFsStacksCommentss) {
				foreach ((array) $this->collFsStacksCommentss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collFsStacksGroupss = null;
		$this->collFsStacksCommentss = null;
			$this->aFsFilms = null;
			$this->asfGuardUser = null;
			$this->aFsStacksWords = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseFsStacks:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseFsStacks::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseFsStacks
