<?php

/**
 * Base class that represents a row from the 'fs_films' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Mar 11 23:15:47 2009
 *
 * @package    lib.model.om
 */
abstract class BaseFsFilms extends BaseObject  implements Persistent {


  const PEER = 'FsFilmsPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FsFilmsPeer
	 */
	protected static $peer;

	/**
	 * The value for the film_id field.
	 * @var        int
	 */
	protected $film_id;

	/**
	 * The value for the film_title field.
	 * @var        string
	 */
	protected $film_title;

	/**
	 * The value for the film_wikipedia_title field.
	 * @var        string
	 */
	protected $film_wikipedia_title;

	/**
	 * The value for the film_wikipedia_poster field.
	 * @var        string
	 */
	protected $film_wikipedia_poster;

	/**
	 * The value for the film_wikipedia_summary field.
	 * @var        string
	 */
	protected $film_wikipedia_summary;

	/**
	 * The value for the film_release field.
	 * @var        string
	 */
	protected $film_release;

	/**
	 * The value for the film_wikipedia_revision field.
	 * @var        int
	 */
	protected $film_wikipedia_revision;

	/**
	 * The value for the next_sync field.
	 * @var        string
	 */
	protected $next_sync;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * @var        array FsStacks[] Collection to store aggregation of FsStacks objects.
	 */
	protected $collFsStackss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFsStackss.
	 */
	private $lastFsStacksCriteria = null;

	/**
	 * @var        array FsFilmsReviews[] Collection to store aggregation of FsFilmsReviews objects.
	 */
	protected $collFsFilmsReviewss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFsFilmsReviewss.
	 */
	private $lastFsFilmsReviewsCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseFsFilms object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [film_id] column value.
	 * 
	 * @return     int
	 */
	public function getFilmId()
	{
		return $this->film_id;
	}

	/**
	 * Get the [film_title] column value.
	 * 
	 * @return     string
	 */
	public function getFilmTitle()
	{
		return $this->film_title;
	}

	/**
	 * Get the [film_wikipedia_title] column value.
	 * 
	 * @return     string
	 */
	public function getFilmWikipediaTitle()
	{
		return $this->film_wikipedia_title;
	}

	/**
	 * Get the [film_wikipedia_poster] column value.
	 * 
	 * @return     string
	 */
	public function getFilmWikipediaPoster()
	{
		return $this->film_wikipedia_poster;
	}

	/**
	 * Get the [film_wikipedia_summary] column value.
	 * 
	 * @return     string
	 */
	public function getFilmWikipediaSummary()
	{
		return $this->film_wikipedia_summary;
	}

	/**
	 * Get the [optionally formatted] temporal [film_release] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFilmRelease($format = 'Y-m-d')
	{
		if ($this->film_release === null) {
			return null;
		}


		if ($this->film_release === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->film_release);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->film_release, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [film_wikipedia_revision] column value.
	 * 
	 * @return     int
	 */
	public function getFilmWikipediaRevision()
	{
		return $this->film_wikipedia_revision;
	}

	/**
	 * Get the [optionally formatted] temporal [next_sync] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getNextSync($format = 'Y-m-d H:i:s')
	{
		if ($this->next_sync === null) {
			return null;
		}


		if ($this->next_sync === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->next_sync);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->next_sync, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [film_id] column.
	 * 
	 * @param      int $v new value
	 * @return     FsFilms The current object (for fluent API support)
	 */
	public function setFilmId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->film_id !== $v) {
			$this->film_id = $v;
			$this->modifiedColumns[] = FsFilmsPeer::FILM_ID;
		}

		return $this;
	} // setFilmId()

	/**
	 * Set the value of [film_title] column.
	 * 
	 * @param      string $v new value
	 * @return     FsFilms The current object (for fluent API support)
	 */
	public function setFilmTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->film_title !== $v) {
			$this->film_title = $v;
			$this->modifiedColumns[] = FsFilmsPeer::FILM_TITLE;
		}

		return $this;
	} // setFilmTitle()

	/**
	 * Set the value of [film_wikipedia_title] column.
	 * 
	 * @param      string $v new value
	 * @return     FsFilms The current object (for fluent API support)
	 */
	public function setFilmWikipediaTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->film_wikipedia_title !== $v) {
			$this->film_wikipedia_title = $v;
			$this->modifiedColumns[] = FsFilmsPeer::FILM_WIKIPEDIA_TITLE;
		}

		return $this;
	} // setFilmWikipediaTitle()

	/**
	 * Set the value of [film_wikipedia_poster] column.
	 * 
	 * @param      string $v new value
	 * @return     FsFilms The current object (for fluent API support)
	 */
	public function setFilmWikipediaPoster($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->film_wikipedia_poster !== $v) {
			$this->film_wikipedia_poster = $v;
			$this->modifiedColumns[] = FsFilmsPeer::FILM_WIKIPEDIA_POSTER;
		}

		return $this;
	} // setFilmWikipediaPoster()

	/**
	 * Set the value of [film_wikipedia_summary] column.
	 * 
	 * @param      string $v new value
	 * @return     FsFilms The current object (for fluent API support)
	 */
	public function setFilmWikipediaSummary($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->film_wikipedia_summary !== $v) {
			$this->film_wikipedia_summary = $v;
			$this->modifiedColumns[] = FsFilmsPeer::FILM_WIKIPEDIA_SUMMARY;
		}

		return $this;
	} // setFilmWikipediaSummary()

	/**
	 * Sets the value of [film_release] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     FsFilms The current object (for fluent API support)
	 */
	public function setFilmRelease($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->film_release !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->film_release !== null && $tmpDt = new DateTime($this->film_release)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->film_release = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = FsFilmsPeer::FILM_RELEASE;
			}
		} // if either are not null

		return $this;
	} // setFilmRelease()

	/**
	 * Set the value of [film_wikipedia_revision] column.
	 * 
	 * @param      int $v new value
	 * @return     FsFilms The current object (for fluent API support)
	 */
	public function setFilmWikipediaRevision($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->film_wikipedia_revision !== $v) {
			$this->film_wikipedia_revision = $v;
			$this->modifiedColumns[] = FsFilmsPeer::FILM_WIKIPEDIA_REVISION;
		}

		return $this;
	} // setFilmWikipediaRevision()

	/**
	 * Sets the value of [next_sync] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     FsFilms The current object (for fluent API support)
	 */
	public function setNextSync($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->next_sync !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->next_sync !== null && $tmpDt = new DateTime($this->next_sync)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->next_sync = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FsFilmsPeer::NEXT_SYNC;
			}
		} // if either are not null

		return $this;
	} // setNextSync()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     FsFilms The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FsFilmsPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     FsFilms The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = FsFilmsPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->film_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->film_title = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->film_wikipedia_title = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->film_wikipedia_poster = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->film_wikipedia_summary = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->film_release = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->film_wikipedia_revision = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->next_sync = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->updated_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = FsFilmsPeer::NUM_COLUMNS - FsFilmsPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating FsFilms object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FsFilmsPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FsFilmsPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collFsStackss = null;
			$this->lastFsStacksCriteria = null;

			$this->collFsFilmsReviewss = null;
			$this->lastFsFilmsReviewsCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFsFilms:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FsFilmsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			FsFilmsPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseFsFilms:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFsFilms:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(FsFilmsPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(FsFilmsPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FsFilmsPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseFsFilms:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			FsFilmsPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FsFilmsPeer::FILM_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FsFilmsPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setFilmId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FsFilmsPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collFsStackss !== null) {
				foreach ($this->collFsStackss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collFsFilmsReviewss !== null) {
				foreach ($this->collFsFilmsReviewss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = FsFilmsPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collFsStackss !== null) {
					foreach ($this->collFsStackss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collFsFilmsReviewss !== null) {
					foreach ($this->collFsFilmsReviewss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FsFilmsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getFilmId();
				break;
			case 1:
				return $this->getFilmTitle();
				break;
			case 2:
				return $this->getFilmWikipediaTitle();
				break;
			case 3:
				return $this->getFilmWikipediaPoster();
				break;
			case 4:
				return $this->getFilmWikipediaSummary();
				break;
			case 5:
				return $this->getFilmRelease();
				break;
			case 6:
				return $this->getFilmWikipediaRevision();
				break;
			case 7:
				return $this->getNextSync();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			case 9:
				return $this->getUpdatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FsFilmsPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getFilmId(),
			$keys[1] => $this->getFilmTitle(),
			$keys[2] => $this->getFilmWikipediaTitle(),
			$keys[3] => $this->getFilmWikipediaPoster(),
			$keys[4] => $this->getFilmWikipediaSummary(),
			$keys[5] => $this->getFilmRelease(),
			$keys[6] => $this->getFilmWikipediaRevision(),
			$keys[7] => $this->getNextSync(),
			$keys[8] => $this->getCreatedAt(),
			$keys[9] => $this->getUpdatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FsFilmsPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setFilmId($value);
				break;
			case 1:
				$this->setFilmTitle($value);
				break;
			case 2:
				$this->setFilmWikipediaTitle($value);
				break;
			case 3:
				$this->setFilmWikipediaPoster($value);
				break;
			case 4:
				$this->setFilmWikipediaSummary($value);
				break;
			case 5:
				$this->setFilmRelease($value);
				break;
			case 6:
				$this->setFilmWikipediaRevision($value);
				break;
			case 7:
				$this->setNextSync($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
			case 9:
				$this->setUpdatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FsFilmsPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setFilmId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setFilmTitle($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFilmWikipediaTitle($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFilmWikipediaPoster($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFilmWikipediaSummary($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFilmRelease($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFilmWikipediaRevision($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setNextSync($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setUpdatedAt($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FsFilmsPeer::DATABASE_NAME);

		if ($this->isColumnModified(FsFilmsPeer::FILM_ID)) $criteria->add(FsFilmsPeer::FILM_ID, $this->film_id);
		if ($this->isColumnModified(FsFilmsPeer::FILM_TITLE)) $criteria->add(FsFilmsPeer::FILM_TITLE, $this->film_title);
		if ($this->isColumnModified(FsFilmsPeer::FILM_WIKIPEDIA_TITLE)) $criteria->add(FsFilmsPeer::FILM_WIKIPEDIA_TITLE, $this->film_wikipedia_title);
		if ($this->isColumnModified(FsFilmsPeer::FILM_WIKIPEDIA_POSTER)) $criteria->add(FsFilmsPeer::FILM_WIKIPEDIA_POSTER, $this->film_wikipedia_poster);
		if ($this->isColumnModified(FsFilmsPeer::FILM_WIKIPEDIA_SUMMARY)) $criteria->add(FsFilmsPeer::FILM_WIKIPEDIA_SUMMARY, $this->film_wikipedia_summary);
		if ($this->isColumnModified(FsFilmsPeer::FILM_RELEASE)) $criteria->add(FsFilmsPeer::FILM_RELEASE, $this->film_release);
		if ($this->isColumnModified(FsFilmsPeer::FILM_WIKIPEDIA_REVISION)) $criteria->add(FsFilmsPeer::FILM_WIKIPEDIA_REVISION, $this->film_wikipedia_revision);
		if ($this->isColumnModified(FsFilmsPeer::NEXT_SYNC)) $criteria->add(FsFilmsPeer::NEXT_SYNC, $this->next_sync);
		if ($this->isColumnModified(FsFilmsPeer::CREATED_AT)) $criteria->add(FsFilmsPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(FsFilmsPeer::UPDATED_AT)) $criteria->add(FsFilmsPeer::UPDATED_AT, $this->updated_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FsFilmsPeer::DATABASE_NAME);

		$criteria->add(FsFilmsPeer::FILM_ID, $this->film_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getFilmId();
	}

	/**
	 * Generic method to set the primary key (film_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setFilmId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of FsFilms (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFilmTitle($this->film_title);

		$copyObj->setFilmWikipediaTitle($this->film_wikipedia_title);

		$copyObj->setFilmWikipediaPoster($this->film_wikipedia_poster);

		$copyObj->setFilmWikipediaSummary($this->film_wikipedia_summary);

		$copyObj->setFilmRelease($this->film_release);

		$copyObj->setFilmWikipediaRevision($this->film_wikipedia_revision);

		$copyObj->setNextSync($this->next_sync);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getFsStackss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFsStacks($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getFsFilmsReviewss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFsFilmsReviews($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setFilmId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     FsFilms Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FsFilmsPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FsFilmsPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collFsStackss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFsStackss()
	 */
	public function clearFsStackss()
	{
		$this->collFsStackss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFsStackss collection (array).
	 *
	 * By default this just sets the collFsStackss collection to an empty array (like clearcollFsStackss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFsStackss()
	{
		$this->collFsStackss = array();
	}

	/**
	 * Gets an array of FsStacks objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this FsFilms has previously been saved, it will retrieve
	 * related FsStackss from storage. If this FsFilms is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array FsStacks[]
	 * @throws     PropelException
	 */
	public function getFsStackss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsFilmsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFsStackss === null) {
			if ($this->isNew()) {
			   $this->collFsStackss = array();
			} else {

				$criteria->add(FsStacksPeer::FILM_ID, $this->film_id);

				FsStacksPeer::addSelectColumns($criteria);
				$this->collFsStackss = FsStacksPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FsStacksPeer::FILM_ID, $this->film_id);

				FsStacksPeer::addSelectColumns($criteria);
				if (!isset($this->lastFsStacksCriteria) || !$this->lastFsStacksCriteria->equals($criteria)) {
					$this->collFsStackss = FsStacksPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFsStacksCriteria = $criteria;
		return $this->collFsStackss;
	}

	/**
	 * Returns the number of related FsStacks objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related FsStacks objects.
	 * @throws     PropelException
	 */
	public function countFsStackss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsFilmsPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFsStackss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FsStacksPeer::FILM_ID, $this->film_id);

				$count = FsStacksPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FsStacksPeer::FILM_ID, $this->film_id);

				if (!isset($this->lastFsStacksCriteria) || !$this->lastFsStacksCriteria->equals($criteria)) {
					$count = FsStacksPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collFsStackss);
				}
			} else {
				$count = count($this->collFsStackss);
			}
		}
		$this->lastFsStacksCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a FsStacks object to this object
	 * through the FsStacks foreign key attribute.
	 *
	 * @param      FsStacks $l FsStacks
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFsStacks(FsStacks $l)
	{
		if ($this->collFsStackss === null) {
			$this->initFsStackss();
		}
		if (!in_array($l, $this->collFsStackss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFsStackss, $l);
			$l->setFsFilms($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this FsFilms is new, it will return
	 * an empty collection; or if this FsFilms has previously
	 * been saved, it will retrieve related FsStackss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in FsFilms.
	 */
	public function getFsStackssJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsFilmsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFsStackss === null) {
			if ($this->isNew()) {
				$this->collFsStackss = array();
			} else {

				$criteria->add(FsStacksPeer::FILM_ID, $this->film_id);

				$this->collFsStackss = FsStacksPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FsStacksPeer::FILM_ID, $this->film_id);

			if (!isset($this->lastFsStacksCriteria) || !$this->lastFsStacksCriteria->equals($criteria)) {
				$this->collFsStackss = FsStacksPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastFsStacksCriteria = $criteria;

		return $this->collFsStackss;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this FsFilms is new, it will return
	 * an empty collection; or if this FsFilms has previously
	 * been saved, it will retrieve related FsStackss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in FsFilms.
	 */
	public function getFsStackssJoinFsStacksWords($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsFilmsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFsStackss === null) {
			if ($this->isNew()) {
				$this->collFsStackss = array();
			} else {

				$criteria->add(FsStacksPeer::FILM_ID, $this->film_id);

				$this->collFsStackss = FsStacksPeer::doSelectJoinFsStacksWords($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FsStacksPeer::FILM_ID, $this->film_id);

			if (!isset($this->lastFsStacksCriteria) || !$this->lastFsStacksCriteria->equals($criteria)) {
				$this->collFsStackss = FsStacksPeer::doSelectJoinFsStacksWords($criteria, $con, $join_behavior);
			}
		}
		$this->lastFsStacksCriteria = $criteria;

		return $this->collFsStackss;
	}

	/**
	 * Clears out the collFsFilmsReviewss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFsFilmsReviewss()
	 */
	public function clearFsFilmsReviewss()
	{
		$this->collFsFilmsReviewss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFsFilmsReviewss collection (array).
	 *
	 * By default this just sets the collFsFilmsReviewss collection to an empty array (like clearcollFsFilmsReviewss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFsFilmsReviewss()
	{
		$this->collFsFilmsReviewss = array();
	}

	/**
	 * Gets an array of FsFilmsReviews objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this FsFilms has previously been saved, it will retrieve
	 * related FsFilmsReviewss from storage. If this FsFilms is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array FsFilmsReviews[]
	 * @throws     PropelException
	 */
	public function getFsFilmsReviewss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsFilmsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFsFilmsReviewss === null) {
			if ($this->isNew()) {
			   $this->collFsFilmsReviewss = array();
			} else {

				$criteria->add(FsFilmsReviewsPeer::FILM_ID, $this->film_id);

				FsFilmsReviewsPeer::addSelectColumns($criteria);
				$this->collFsFilmsReviewss = FsFilmsReviewsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FsFilmsReviewsPeer::FILM_ID, $this->film_id);

				FsFilmsReviewsPeer::addSelectColumns($criteria);
				if (!isset($this->lastFsFilmsReviewsCriteria) || !$this->lastFsFilmsReviewsCriteria->equals($criteria)) {
					$this->collFsFilmsReviewss = FsFilmsReviewsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFsFilmsReviewsCriteria = $criteria;
		return $this->collFsFilmsReviewss;
	}

	/**
	 * Returns the number of related FsFilmsReviews objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related FsFilmsReviews objects.
	 * @throws     PropelException
	 */
	public function countFsFilmsReviewss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsFilmsPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFsFilmsReviewss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FsFilmsReviewsPeer::FILM_ID, $this->film_id);

				$count = FsFilmsReviewsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FsFilmsReviewsPeer::FILM_ID, $this->film_id);

				if (!isset($this->lastFsFilmsReviewsCriteria) || !$this->lastFsFilmsReviewsCriteria->equals($criteria)) {
					$count = FsFilmsReviewsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collFsFilmsReviewss);
				}
			} else {
				$count = count($this->collFsFilmsReviewss);
			}
		}
		$this->lastFsFilmsReviewsCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a FsFilmsReviews object to this object
	 * through the FsFilmsReviews foreign key attribute.
	 *
	 * @param      FsFilmsReviews $l FsFilmsReviews
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFsFilmsReviews(FsFilmsReviews $l)
	{
		if ($this->collFsFilmsReviewss === null) {
			$this->initFsFilmsReviewss();
		}
		if (!in_array($l, $this->collFsFilmsReviewss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFsFilmsReviewss, $l);
			$l->setFsFilms($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this FsFilms is new, it will return
	 * an empty collection; or if this FsFilms has previously
	 * been saved, it will retrieve related FsFilmsReviewss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in FsFilms.
	 */
	public function getFsFilmsReviewssJoinsfGuardUser($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FsFilmsPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFsFilmsReviewss === null) {
			if ($this->isNew()) {
				$this->collFsFilmsReviewss = array();
			} else {

				$criteria->add(FsFilmsReviewsPeer::FILM_ID, $this->film_id);

				$this->collFsFilmsReviewss = FsFilmsReviewsPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(FsFilmsReviewsPeer::FILM_ID, $this->film_id);

			if (!isset($this->lastFsFilmsReviewsCriteria) || !$this->lastFsFilmsReviewsCriteria->equals($criteria)) {
				$this->collFsFilmsReviewss = FsFilmsReviewsPeer::doSelectJoinsfGuardUser($criteria, $con, $join_behavior);
			}
		}
		$this->lastFsFilmsReviewsCriteria = $criteria;

		return $this->collFsFilmsReviewss;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collFsStackss) {
				foreach ((array) $this->collFsStackss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collFsFilmsReviewss) {
				foreach ((array) $this->collFsFilmsReviewss as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collFsStackss = null;
		$this->collFsFilmsReviewss = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseFsFilms:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseFsFilms::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseFsFilms
