default:
  http_metas:
    content-type: text/html

  metas:
    title:        Filmstacks
    description:  Filmstacks allows you to track and share the films you watch with friends in an innovative and fun manner.
    keywords:     Filmstacks, Film, Films, Movie, Movies, Cinema, Cinemas, Review, Reviews, Flick, Flicks, Screenings, Tracking, Showings, Showing, Stacked, Feed, Feeds, Social, Networking, Lifestream, Lifestreaming, App, Stacking, Stacks, Stack, Nick, Nicholas, Pellant, Lewis, Forbes
    language:     en

  has_layout:     on
  layout:         master
  stylesheets:    [global/master.css, /js/jq/slimbox/css/slimbox2.css]
  javascripts:    [http://jqueryjs.googlecode.com/files/jquery-1.3.2.min.js, jq/slimbox/js/slimbox2.js]